server:
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: outstagram
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/success-codes: '200,302'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:${AWS_ACCOUNT_ID}:certificate/{$IDENTIFIER}
      external-dns.alpha.kubernetes.io/hostname: argocd.outstagram.shop
    ingressClassName: "alb"
    hosts:
      - argocd.outstagram.shop
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80

global:
  domain: argocd.outstagram.shop

configs:
  params:
    server.insecure: true