serviceAccount:
  create: true
  name: loki
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::${AWS_ACCOUNT_ID}:role/outstagram-dev-loki-role"

loki:
  auth_enabled: false
  useTestSchema: false
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: s3
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
  storage:
    type: "s3"
    s3:
      region: ap-northeast-2
    bucketNames:
      chunks: outstagram-dev-loki-bucket
      ruler: outstagram-dev-loki-bucket
      admin: outstagram-dev-loki-bucket

test:
  enabled: false

write:
  resources: 
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi