apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feed-server
  namespace: argocd
spec:
  destination:
    name: arn:aws:eks:ap-northeast-2:${AWS_ACCOUNT_ID}:cluster/outstagram-dev-cluster
    namespace: sns
  project: default
  source:
    helm:
      releaseName: feed-server
      valueFiles:
      - ci/outstagram-values.yaml
    path: sns/feed-server
    repoURL: https://github.com/subiin/outstagram-helm.git
    targetRevision: HEAD