apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sns-frontend
  namespace: argocd
spec:
  destination:
    name: arn:aws:eks:ap-northeast-2:${AWS_ACCOUNT_ID}:cluster/outstagram-dev-cluster
    namespace: sns
  project: default
  source:
    helm:
      releaseName: sns-frontend
      valueFiles:
      - ci/outstagram-values.yaml
    path: sns/sns-frontend
    repoURL: https://github.com/subiin/outstagram-helm.git
    targetRevision: HEAD