apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timeline-server
  namespace: argocd
spec:
  destination:
    name: arn:aws:eks:ap-northeast-2:975050179689:cluster/outstagram-dev-cluster
    namespace: sns
  project: default
  source:
    helm:
      releaseName: timeline-server
      valueFiles:
      - ci/outstagram-values.yaml
    path: sns/timeline-server
    repoURL: https://github.com/subiin/outstagram-helm.git
    targetRevision: HEAD