appName: sns-frontend
replicas: 1
imageTag: 1.0.0
profile: dev
envs: []
configs: []
resources:
  memory:
    requests: "256Mi"
    limits: "500Mi"
  cpu:
    requests: "250m"
    limits: "500m"
probe: false
persistence:
  enabled: false
ingress:
  enabled: true
  hostname: outstagram.shop
  path: /
  pathType: Prefix
  port: 3000