appName: sns-frontend
replicas: 1
imageTag: 1.0.0
profile: dev
envs: []
configs: []
probe: false
persistence:
  enabled: true
  volume:
    - name: logs
      claimName: spring-app-logs
      mountPath: /logs
ingress:
  enabled: true
  hostname: outstagram.shop
  port: 3000
  paths:
    - path: /
      pathType: Prefix
podAntiAffinity:
  enabled: true