name: Timeline CI

on:
  push:
    paths:
    - 'timeline-server/**'
    tags:
    - 't_*'
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        redis-version: [6.2.4-v4, 6.2.6-v3]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Make application.yaml
      run: |
        cd timeline-server
        touch ./src/main/resources/application.yaml
        echo "${{ secrets.AWS_TIMELINE_PROPERTIES }}" > ./src/main/resources/application.yaml

    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-image: redis/redis-stack-server
        redis-version: ${{ matrix.redis-version }}

    - name: Start Bitnami Kafka
      uses: bbcCorp/kafka-actions@v1

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x ./timeline-server/gradlew

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_CI_ROLE }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract tag name
      id: extract_tag
      shell: bash
      run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Confirm Image Tag
      run: echo $IMAGE_TAG

    - name: Build with Gradle
      run: |
        cd timeline-server
        ./gradlew build

    - name: Build and Push Docker image with Jib
      run: |
        cd timeline-server
        ./gradlew jib --image=${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_TIMELINE_SERVER_REPO }}:${{ env.IMAGE_TAG }}